<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<EnableSdkContainerDebugging>True</EnableSdkContainerDebugging>
		<ContainerBaseImage>mcr.microsoft.com/dotnet/aspnet:10.0</ContainerBaseImage>
		<UserSecretsId>06017c20-6b39-45d3-bcb4-fb1bc4797ff3</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Scalar.AspNetCore" />
		<PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="Aspire.RabbitMQ.Client" />
		<PackageReference Include="MassTransit.RabbitMQ" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
	</ItemGroup>

	<ItemGroup>
		<ContainerPort Include="8081" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ServiceDefaults\ServiceDefaults.csproj" />
		<ProjectReference Include="..\OrderService.Infrastructure\OrderService.Infrastructure.csproj" />
		<ProjectReference Include="..\OrderService.Contracts\OrderService.Contracts.csproj" />
	</ItemGroup>

</Project>
