<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared.Domain\Shared.Domain.csproj" />
    <ProjectReference Include="..\InventoryService.Contracts\InventoryService.Contracts.csproj" />
    <ProjectReference Include="..\Shared.Common\Shared.Common.csproj" />
  </ItemGroup>

</Project>
